
PORT: 8082
DB_USERNAME: ${db-dev-username}
DB_PASSWORD: ${db-dev-password}
DB_HOST: 68.183.225.48
DB_PORT: 28000
DB_NAME: testing_product_and_upload_file
AUTHENTICATION-DATABASE: admin

MINIO_URL: http://68.183.225.48:9000
MINIO_ACCESS_KEY: ${minio-access-key}
MINIO_SECRETE_KEY: ${minio-secret-key}
MINIO_BUCKET: origin-bucket-1

MEDIA_BASE_URI: https://file-origin.devkh.asia
MEDIA_ENDPOINT: /api/v1/files

#MEDIA_BASE_URI: http://127.0.0.1:8080

TELEGRAM_TOKEN: ${telegram-token}
#TELEGRAM_USERNAME: istad_admission_bot
TELEGRAM_ID: ${telegram-id}