server:
  port: 8084

spring:
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: my-provider
            client-id: ${client-id}
            client-secret: ${secret}
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8084/login/oauth2/code/oidc-client
            client-authentication-method:
              - client_secret_post
              - client_secret_basic
            scope:
              - openid

        provider:
          my-provider:
            authorization-uri: http://localhost:8080/oauth2/authorize

            token-uri: http://localhost:8080/oauth2/token

            user-info-uri: http://localhost:8080/oauth2/userinfo

            issuer-uri: http://localhost:8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security.oauth2.client: DEBUG

